[package]
name = "raftbare"
version = "0.2.2"
edition = "2024"
authors = ["Takeru Ohta <phjgt308@gmail.com>"]
license = "MIT"
description = "Minimal but feature-complete, I/O-free implementation of Raft distributed consensus algorithm"
homepage = "https://github.com/sile/raftbare"
repository = "https://github.com/sile/raftbare"
readme = "README.md"

[dependencies]

[dev-dependencies]
rand = "0.9.2"
